<?php
/*
 * Модуль ruswebs_entities_lists
 */

define('REL_URL_ADMIN', 'admin/content/ruswebs-entities-lists');
define('REL_URL_ADMIN_ADD_LIST', REL_URL_ADMIN.'/add-list');

/**
 * Implements hook_init().
 */
function ruswebs_entities_lists_init() {
	$module_path = drupal_get_path('module', 'ruswebs_entities_lists');
	require_once($module_path . '/rel_list.class.inc');	
	require_once($module_path . '/rel_lists_collection.class.inc');	
}
/**
 * Implementation of hook_menu().
 */
function ruswebs_entities_lists_menu() {
	$items[REL_URL_ADMIN . '/lists'] = array(
		'title' => t('Lists'),
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'rel_lists_collection_page',
		'access arguments' => array('admin entities lists'),
		'file' => '/rel_lists_collection.admin.inc',
	);

	$items[REL_URL_ADMIN . '/list/%/params'] = array(
		'title' => t('Edit list'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('rel_admin_list_form', 4),
		'access arguments' => array('admin entities lists'),
		'file' => 'rel_list.admin.inc',
	);

	$items[REL_URL_ADMIN . '/list/%/entities'] = array(
		'title' => t('Entities of list'),
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('rel_admin_list_entities_form', 4),
		'access arguments' => array('admin entities lists'),
		'file' => 'rel_list.admin.inc',
	);


	$items[REL_URL_ADMIN_ADD_LIST] = array(
		'title' => t('Add list'),
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('rel_admin_list_form'),
		'access arguments' => array('admin entities lists'),
		'file' => 'rel_list.admin.inc',
	);

	$items['ruswebs-entities-lists/get-available-entities'] = array(
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'rel_get_available_entities',
		'page arguments' => array(2),
		'access arguments' => array('admin entities lists'),
		'file' => 'rel_list.admin.inc',
	);
	
	return $items;
}
function ruswebs_entities_lists_theme() {
	$module_path = drupal_get_path('module', 'ruswebs_entities_lists');
	return array(
		'lists_collection_page' => array(
			'template' => 'lists_collection_page',
			'path' => $module_path . '/tpl',
			'variables' => array(
				'lists' => NULL,
			),
		),
		'rel_admin_list_entities_form' => array(
			'render element' => 'form',
			'file' => 'rel_list.admin.inc',
		),
	);
}
/**
 * Implements hook_permission().
 */
function ruswebs_entities_lists_permission() {
	return array(
		'admin entities lists' => array(
			'title' => t('admin entities lists'),
			'description' => t('Rights for adding and manage lists entities (module ruswebs_entities_lists).'),
		),
	);
}
